name: Windows

on:
  push:
    tags:
      - 'v*'
    branches: [ master ]

  pull_request:
    branches: [ master] 
    types: [ opened, synchronize, reopened ]

  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  build-and-release:
    name: Build on Windows

    runs-on: windows-latest

    steps:
      # install Qt SDK
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '5.15.*'
          cache: 'true'
  
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      # CMake Config
      - name: Configure Cmake
        run: cmake -B build -S . -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      
      # Cmake Build
      - name: Build Project
        run: cmake --build build --config ${{env.BUILD_TYPE}}

      # 添加以下内容：运行测试
      - name: Run Tests
        working-directory: ${{ github.workspace }}/build
        run: ctest --output-on-failure --build-config ${{env.BUILD_TYPE}}

      - name: Package Application (Windows)
        if: github.ref_type == 'tag'
        shell: pwsh
        env: 
          TAG_NAME: ${{ github.ref_name }}
        run: |
          New-Item -ItemType Directory -Path package
          Copy-Item build/code/Release/*.exe package/
          windeployqt --qmldir . package/SSHTunnelManager.exe
          Compress-Archive -Path package/* -DestinationPath "SSHTunnelManager-windows-${env:TAG_NAME}.zip"

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v3
        if: github.ref_type == 'tag'
        with:
          files: |
            SSHTunnelManager-windows-${{ github.ref_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}